service: ttc-private-service
frameworkVersion: "2"
provider:
  name: aws
  region: eu-central-1
  runtime: nodejs14.x

functions:
  parseArrivalTimes:
    handler: handler.parseArrivalTimes
    timeout: 30
    events:
      - http:
          path: parse-arrival-times
          method: get

package:
  excludeDevDependencies: false
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"
